### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by hazardfn** [mtwilliams/bourne#3]
Hey,

Been spending a while looking at your code and couldn't work out what happens if the app/server/gen_stage process crashes?

Does it pick up where it left off on restart or does it go ahead (using your example) and re-read everyone born before 1980? Am I wrong in assuming this is an infinite stream?

```elixir
import Ecto.Query
q = from(actor in Actor, where: actor.born <= 1980)

# You can stream through an `Enumerable`:
My.Repo.stream(q) |> Stream.each(&IO.inspect) |> Stream.run
```

**Comment by mtwilliams** [comment]
Hi!

The example you gave doesn't use `GenStage` it uses an `Enumerable` which is reduced in the calling process. That means if you're using `keyset` based pagination it will construct a `Bourne.Stream` and enumerate that. In which case it will restart the stream should the process crash. If you're using `cursor` based pagination it will use Ecto's default behavior which should have similar behavior.

Regarding the behavior of `Bourne.Streamer` (which you start using `My.Repo.streamer(q)`):

It will start a `GenStage` producer that will return rows as demanded by subscribers. Should it crash (say to the database becoming unreachable) it will lose it's position. There's no good one-size-fits all strategy for dealing with that. If you need to work around transient issues that will cause it to crash, I would suggest having an intermediary process or stage that tracks a watermark and uses that to restart streaming should the producer crash.

[Also, should all consumers unsubscribe (or crash) the producer will stop and lose it's position.](https://github.com/mtwilliams/bourne/blob/master/lib/bourne/streamer.ex#L52) I could expose an option that keeps the producer around until the stream is exhausted. That would allow consumers to crash and reconnect to the producer. However, that means you can lose rows. Similarly, I would suggest you introduce an intermediary process or stage that ensures reliable consumption of rows.

Does that help?

**Comment by hazardfn** [comment]
@mtwilliams Great thank you! Very informative, we'll probably build an intermediary stage that saves the last key it received somewhere, then on restart build a dynamic query that looks up that last saved key on restart and does a `WHERE ^key > ^x`.

**Comment by mtwilliams** [comment]
Glad to hear, @hazardfn.
